### ISSUE TITLE
compile issue on rxjs@beta.8 and typescript@next

### ISSUE THREAD

**Issue by hlobil** [ngrx/core#1]
4 export declare class SyncSubject<T> extends Subject<T> {
                       ~~~~~~~~~~~

node_modules/@ngrx/core/SyncSubject.d.ts(4,22): error TS2415: Class 'SyncSubject<T>' incorrectly extends base class 'Subject<T>'.
  Types of property '_subscribe' are incompatible.
    Type '(subscriber: Subscriber<T>) => AnonymousSubscription | Function | void' is not assignable to type '(subscriber: Subscriber<T>) => Subscription'.
      Type 'AnonymousSubscription | Function | void' is not assignable to type 'Subscription'.
        Type 'AnonymousSubscription' is not assignable to type 'Subscription'.
          Property 'isUnsubscribed' is missing in type 'AnonymousSubscription'.

**Comment by damsorian** [comment]
The same issue....

**Comment by patrickkeller** [comment]
The same problem happens with typescript@1.8.X and rxjs@5.0.0-beta.9 (downgrade to beta 6 doesn't help..)

**Comment by petebacondarwin** [comment]
This is due to a breaking change in `RxJS@5.0.0.-beta-8'. See https://github.com/ReactiveX/RxJS/commit/ba9ef2b#diff-c745ba5bcc0e744ecdcc572424f38498L3

**Comment by sv2dev** [comment]
Is the dependency usage going to be updated soon?
Angular 2 now depends on `5.0.0-beta.11` since [this commit](https://github.com/angular/angular/commit/ca41b4f5ff400d604d60feeef7dfacf8436cb0f7).
Only ngrx is keeping me from updating my project dependency now.

**EDIT:**
I just saw that this project now depends on `5.0.0-beta.11` as well.
So this issue should be resolved now, right?

**Comment by brandonroberts** [comment]
Issue has been resolved with RxJS 5.x being released
